export const BRANCHES = {
  master: {
    key: 'master',
    label: 'Master',
    baseUrl: 'https://distributed-tracing-system.vercel.app',
    policy: {
      projectName: 'dts',
      branchName: 'main',
      captureSlow: 200,
      captureCodes: [4, 5],
    },
  },
  development: {
    key: 'development',
    label: 'Development',
    baseUrl: 'https://distributed-tracing-system.onrender.com',
    policy: {
      projectName: 'dts',
      branchName: 'dev',
      captureSlow: 0,
      captureCodes: [1, 2, 3, 4, 5],
    },
  },
};

export const ENDPOINTS = [
  {
    id: 'wake-up',
    name: 'Wake Up',
    description: 'Warm up server and check redirect behavior.',
    method: 'GET',
    pathTemplate: '/',
    pathParams: [],
    queryParams: [],
    body: '',
    validBranches: ['master', 'development'],
  },
  {
    id: 'test-url',
    name: 'Test URL',
    description: 'Runs test route and returns request trace summary.',
    method: 'GET',
    pathTemplate: '/test',
    pathParams: [],
    queryParams: [{ key: 'url', label: 'Target URL', value: 'https://www.google.com' }],
    body: '',
    validBranches: ['master', 'development'],
  },
  {
    id: 'get-user',
    name: 'Get User',
    description: 'Fetches user details by id.',
    method: 'GET',
    pathTemplate: '/user/:id',
    pathParams: [{ key: 'id', label: 'User ID', value: '0' }],
    queryParams: [],
    body: '',
    validBranches: ['development'],
  },
  {
    id: 'edit-user',
    name: 'Edit User',
    description: 'Edits user when self-authorized.',
    method: 'POST',
    pathTemplate: '/user/:id/edit',
    pathParams: [{ key: 'id', label: 'User ID', value: '1' }],
    queryParams: [],
    body: '{}',
    validBranches: ['development'],
  },
  {
    id: 'delete-user',
    name: 'Delete User',
    description: 'Deletes user (admin-only action).',
    method: 'DELETE',
    pathTemplate: '/user/:id',
    pathParams: [{ key: 'id', label: 'User ID', value: '2' }],
    queryParams: [],
    body: '',
    validBranches: ['development'],
  },
  {
    id: 'delay-response',
    name: 'Delay Response',
    description: 'Simulates latency in seconds.',
    method: 'PUT',
    pathTemplate: '/delay/:time',
    pathParams: [{ key: 'time', label: 'Delay (s)', value: '1' }],
    queryParams: [],
    body: '',
    validBranches: ['master', 'development'],
  },
  {
    id: 'set-status',
    name: 'Set Status',
    description: 'Forces response status code.',
    method: 'PATCH',
    pathTemplate: '/status/:code',
    pathParams: [{ key: 'code', label: 'Status Code', value: '412' }],
    queryParams: [],
    body: '',
    validBranches: ['master', 'development'],
  },
  {
    id: 'logs',
    name: 'Logs',
    description: 'Gets all logs.',
    method: 'GET',
    pathTemplate: '/logs',
    pathParams: [],
    queryParams: [],
    body: '',
    validBranches: ['master', 'development'],
  },
  {
    id: 'filtered-logs',
    name: 'Filtered Logs',
    description: 'Gets logs filtered by status code.',
    method: 'GET',
    pathTemplate: '/logs/:code',
    pathParams: [{ key: 'code', label: 'Status Code', value: '200' }],
    queryParams: [],
    body: '',
    validBranches: ['master', 'development'],
  },
];
